version: "3.9"
services:
  static:
    image: halverneus/static-file-server
    environment:
      - PORT=8080
      - FOLDER=/static
    ports:
      - "8080:8080"
    volumes:
      - ./static:/static
  web-client:
    user: "node"
    image: node:18-alpine
    command: npm run start:dev
    working_dir: "/home/node/app"
    volumes:
      - ./web:/home/node/app
    ports:
      - "8081:8081"
    environment:
      - HTTP_PORT=8081
      - NODE_DEBUG=1
